name: .NET Core CI

on: [pull_request]

jobs:
  test:
    name: Tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v1

    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: Build
      run: dotnet build -warnaserror
    - name: Tests
      run: dotnet test

    - name: Generate XML SBOM
      uses: CycloneDX/gh-dotnet-generate-sbom@master
      with:
        path: 'CoderPatros.AuthenticatedHttpClient.sln'
        githubBearerToken: ${{ secrets.GITHUB_TOKEN }}
