name: Release

on:
  workflow_dispatch

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v1
  
      - name: Setup .NET Core 3.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101

      - name: Package release
        id: package_release
        run: |
          VERSION=`cat semver.txt`
          echo "##[set-output name=version;]$VERSION"
          dotnet test
          dotnet build --configuration Release
          dotnet pack --configuration Release --version-suffix $VERSION --output ./

      - name: Publish package
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          dotnet nuget push --source https://api.nuget.org/v3/index.json --api-key "$NUGET_API_KEY" *.AuthorizationHeader.${{ steps.package_release.outputs.version }}.nupkg
          dotnet nuget push --source https://api.nuget.org/v3/index.json --api-key "$NUGET_API_KEY" *.AzureAd.${{ steps.package_release.outputs.version }}.nupkg
          dotnet nuget push --source https://api.nuget.org/v3/index.json --api-key "$NUGET_API_KEY" *.AzureAppServiceManagedIdentity.${{ steps.package_release.outputs.version }}.nupkg
          dotnet nuget push --source https://api.nuget.org/v3/index.json --api-key "$NUGET_API_KEY" *.Basic.${{ steps.package_release.outputs.version }}.nupkg
          dotnet nuget push --source https://api.nuget.org/v3/index.json --api-key "$NUGET_API_KEY" *.CustomHeader.${{ steps.package_release.outputs.version }}.nupkg
          dotnet nuget push --source https://api.nuget.org/v3/index.json --api-key "$NUGET_API_KEY" *.QueryStringParameter.${{ steps.package_release.outputs.version }}.nupkg

      - name: Create github release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: ${{ steps.package_release.outputs.version }}
          tag_name: v${{ steps.package_release.outputs.version }}
          draft: false
          prerelease: false

      - name: Upload package to github release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: CoderPatros.AuthenticatedHttpClient.AuthorizationHeader.${{ steps.package_release.outputs.version }}.nupkg
          asset_name: CoderPatros.AuthenticatedHttpClient.AuthorizationHeader.${{ steps.package_release.outputs.version }}.nupkg
          asset_content_type: application/zip

      - name: Upload package to github release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: CoderPatros.AuthenticatedHttpClient.AzureAd.${{ steps.package_release.outputs.version }}.nupkg
          asset_name: CoderPatros.AuthenticatedHttpClient.AzureAd.${{ steps.package_release.outputs.version }}.nupkg
          asset_content_type: application/zip

      - name: Upload package to github release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: CoderPatros.AuthenticatedHttpClient.AzureAppServiceManagedIdentity.${{ steps.package_release.outputs.version }}.nupkg
          asset_name: CoderPatros.AuthenticatedHttpClient.AzureAppServiceManagedIdentity.${{ steps.package_release.outputs.version }}.nupkg
          asset_content_type: application/zip

      - name: Upload package to github release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: CoderPatros.AuthenticatedHttpClient.Basic.${{ steps.package_release.outputs.version }}.nupkg
          asset_name: CoderPatros.AuthenticatedHttpClient.Basic.${{ steps.package_release.outputs.version }}.nupkg
          asset_content_type: application/zip

      - name: Upload package to github release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: CoderPatros.AuthenticatedHttpClient.CustomHeader.${{ steps.package_release.outputs.version }}.nupkg
          asset_name: CoderPatros.AuthenticatedHttpClient.CustomHeader.${{ steps.package_release.outputs.version }}.nupkg
          asset_content_type: application/zip

      - name: Upload package to github release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: CoderPatros.AuthenticatedHttpClient.QueryStringParameter.${{ steps.package_release.outputs.version }}.nupkg
          asset_name: CoderPatros.AuthenticatedHttpClient.QueryStringParameter.${{ steps.package_release.outputs.version }}.nupkg
          asset_content_type: application/zip
